use crate::summary::{walk_dir, write_summary};

mod summary;

fn main() {
    const use_header: bool = false;

    let mut path = std::env::args().nth(1).expect("No path provided");
    if !path.ends_with("/") {
        path.push_str("/");
    }
    println!("Autogenerated: {}SUMMARY.md", path);
    let entries = walk_dir(path.clone(), 0, use_header);
    write_summary(entries, &path);
}
