[package]
name = "rs_autobook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
hex = "0.4.3"
md-5 = "0.10.5"
mdbook = "0.4.34"
